# Generated by Django 5.0.2 on 2024-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_colour_size_product_quantity_product_colours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colours',
            field=models.ManyToManyField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('teal', 'Teal'), ('olive', 'Olive'), ('lime', 'Lime'), ('navy', 'Navy'), ('maroon', 'Maroon'), ('silver', 'Silver'), ('gold', 'Gold')], related_name='products', to='shop.colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', '2 Extra Large')], related_name='products', to='shop.size'),
        ),
    ]
